run-01:
	time until PYTHONPATH=`pwd` python tests/o01_test_replays_last.py ; do \
		timenow=timenow+1; \
		sleep 2; \
	done 
	
	@echo "You did it 🙀 !!!";

run-02:
	time until PYTHONPATH=`pwd` python tests/o02_test_majority.py ; do \
		timenow=timenow+1; \
		sleep 2; \
	done 
	
	@echo "Awesome 🙉🚀 !!!";	

run-03:
	time until PYTHONPATH=`pwd` python tests/o03_test_frequency_sorting.py ; do \
		timenow=timenow+1; \
		sleep 2; \
	done 
	
	@echo "Solved!!! Good job 👍";

run-04:
	time until PYTHONPATH=`pwd` python tests/o04_test_how_deep.py ; do \
		timenow=timenow+1; \
		sleep 2; \
	done 
	
	@echo "Hooray!!! You did it! 💥";